# Generated by Django 4.2.13 on 2024-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250, unique=True)),
                ("password", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
